//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace top.ebiz.service
{
    using System;
    using System.Collections.Generic;
    
    public partial class BZ_DOC_TRAVELER
    {
        public string DH_CODE { get; set; }
        public decimal DTL_ID { get; set; }
        public Nullable<decimal> CTN_ID { get; set; }
        public Nullable<decimal> CT_ID { get; set; }
        public Nullable<decimal> PV_ID { get; set; }
        public string CITY_TEXT { get; set; }
        public Nullable<System.DateTime> DTL_BUS_FROMDATE { get; set; }
        public Nullable<System.DateTime> DTL_BUS_TODATE { get; set; }
        public Nullable<System.DateTime> DTL_TRAVEL_FROMDATE { get; set; }
        public Nullable<System.DateTime> DTL_TRAVEL_TODATE { get; set; }
        public Nullable<decimal> DTL_TRAVEL_DAYS { get; set; }
        public string DTL_EMP_ID { get; set; }
        public string DTL_GL_ACCOUNT { get; set; }
        public string DTL_COST_CENTER { get; set; }
        public string DTL_ORDER_WBS { get; set; }
        public string DTL_REMARK { get; set; }
        public string DTL_TOKEN { get; set; }
        public string DTL_FUNCTION { get; set; }
        public string DTL_DEPARTMENT { get; set; }
        public string DTL_DIVISION { get; set; }
        public string DTL_SECTIONS { get; set; }
    }
}
