//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace top.ebiz.service
{
    using System;
    using System.Collections.Generic;
    
    public partial class BZ_DOC_TRAVELER_APPROVER
    {
        public string DH_CODE { get; set; }
        public Nullable<decimal> DTA_ID { get; set; }
        public string DTA_TYPE { get; set; }
        public string DTA_APPR_EMPID { get; set; }
        public string DTA_TRAVEL_EMPID { get; set; }
        public string DTA_REMARK { get; set; }
        public Nullable<decimal> DTA_DOC_STATUS { get; set; }
        public string DTA_APPR_STATUS { get; set; }
        public string DTA_APPR_REMARK { get; set; }
        public Nullable<decimal> DTA_STATUS { get; set; }
        public string DTA_UPDATE_TOKEN { get; set; }
        public Nullable<decimal> DTA_APPR_LEVEL { get; set; }
        public string DTA_APPR_POS { get; set; }
    }
}
