//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace top.ebiz.service
{
    using System;
    using System.Collections.Generic;
    
    public partial class BZ_DOC_ACTION
    {
        public string DA_TOKEN { get; set; }
        public string DH_CODE { get; set; }
        public string DOC_TYPE { get; set; }
        public Nullable<decimal> DOC_STATUS { get; set; }
        public string EMP_ID { get; set; }
        public Nullable<decimal> ACTION_STATUS { get; set; }
        public Nullable<decimal> TAB_NO { get; set; }
        public Nullable<System.DateTime> ACTION_DATE { get; set; }
        public string REMARK { get; set; }
        public string FROM_EMP_ID { get; set; }
        public string ACTION_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
    }
}
