//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace top.ebiz.service
{
    using System;
    using System.Collections.Generic;
    
    public partial class BZ_DOC_RUNNING
    {
        public string DOC_PREFIX { get; set; }
        public Nullable<decimal> DOC_NO { get; set; }
        public string DOC_TYPE { get; set; }
    }
}
