//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace top.ebiz.service
{
    using System;
    using System.Collections.Generic;
    
    public partial class BZ_DOC_CONTIENT
    {
        public string DH_CODE { get; set; }
        public decimal CTN_ID { get; set; }
    }
}
