//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace top.ebiz.service
{
    using System;
    using System.Collections.Generic;
    
    public partial class BZ_DOC_TRAVELER_EXPENSE
    {
        public string DH_CODE { get; set; }
        public decimal DTE_ID { get; set; }
        public string DTE_EMP_ID { get; set; }
        public string DTE_AIR_TECKET { get; set; }
        public string DTE_ACCOMMODATIC { get; set; }
        public string DTE_ALLOWANCE { get; set; }
        public Nullable<decimal> DTE_ALLOWANCE_DAY { get; set; }
        public Nullable<decimal> DTE_ALLOWANCE_NIGHT { get; set; }
        public string DTE_VISA_FREE { get; set; }
        public string DTE_TRAVEL_INS { get; set; }
        public string DTE_TRANSPORT { get; set; }
        public Nullable<System.DateTime> DTE_PASSPORT_VALID { get; set; }
        public string DTE_PASSPORT_EXPENSE { get; set; }
        public Nullable<System.DateTime> DTE_CL_VALID { get; set; }
        public string DTE_CL_EXPENSE { get; set; }
        public string DTE_REGIS_FREE { get; set; }
        public string DTE_MISCELLANEOUS { get; set; }
        public Nullable<decimal> DTE_TOTAL_EXPENSE { get; set; }
        public Nullable<decimal> CT_ID { get; set; }
        public Nullable<decimal> DTE_APPR_STATUS { get; set; }
        public string DTE_APPR_OPT { get; set; }
        public string DTE_APPR_REMARK { get; set; }
        public Nullable<decimal> ID { get; set; }
        public string DTE_TOKEN_UPD { get; set; }
        public Nullable<decimal> DTE_STATUS { get; set; }
        public string DTE_TOKEN { get; set; }
        public Nullable<decimal> DTE_LINE_APPR_STATUS { get; set; }
        public Nullable<decimal> DTE_CAP_APPR_STATUS { get; set; }
        public Nullable<decimal> CTN_ID { get; set; }
        public Nullable<decimal> PV_ID { get; set; }
        public string CITY_TEXT { get; set; }
        public Nullable<System.DateTime> DTE_BUS_FROMDATE { get; set; }
        public Nullable<System.DateTime> DTE_BUS_TODATE { get; set; }
        public Nullable<System.DateTime> DTE_TRAVEL_FROMDATE { get; set; }
        public Nullable<System.DateTime> DTE_TRAVEL_TODATE { get; set; }
        public Nullable<decimal> DTE_TRAVEL_DAYS { get; set; }
        public string DTE_GL_ACCOUNT { get; set; }
        public string DTE_COST_CENTER { get; set; }
        public string DTE_ORDER_WBS { get; set; }
        public string DTE_TRAVELER_REMARK { get; set; }
        public string DTE_CREATE_BY { get; set; }
        public Nullable<System.DateTime> DTE_CREATE_DATE { get; set; }
        public string DTE_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> DTE_UPDATE_DATE { get; set; }
        public string DTE_TOKEN_UPDATE { get; set; }
        public Nullable<decimal> DTE_EXPENSE_CONFIRM { get; set; }
        public string DTE_CAP_APPR_OPT { get; set; }
        public string DTE_CAP_APPR_REMARK { get; set; }

        public string DTE_TRAVELER_REF_ID { get; set; }
    }
}
