//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace top.ebiz.service
{
    using System;
    using System.Collections.Generic;
    
    public partial class BZ_DOC_HEAD
    {
        public string DH_CODE { get; set; }
        public Nullable<decimal> DH_VERSION { get; set; }
        public Nullable<System.DateTime> DH_DATE { get; set; }
        public string DH_COM_CODE { get; set; }
        public string DH_TYPE { get; set; }
        public string DH_BEHALF_EMP_ID { get; set; }
        public string DH_TOPIC { get; set; }
        public string DH_TRAVEL { get; set; }
        public Nullable<System.DateTime> DH_BUS_FROMDATE { get; set; }
        public Nullable<System.DateTime> DH_BUS_TODATE { get; set; }
        public Nullable<System.DateTime> DH_TRAVEL_FROMDATE { get; set; }
        public Nullable<System.DateTime> DH_TRAVEL_TODATE { get; set; }
        public Nullable<decimal> DH_TRAVEL_DAYS { get; set; }
        public string DH_TRAVEL_OBJECT { get; set; }
        public string DH_INITIATOR_EMPID { get; set; }
        public string DH_INITIATOR_REMARK { get; set; }
        public string DH_AFTER_TRIP_OPT1 { get; set; }
        public string DH_AFTER_TRIP_OPT2 { get; set; }
        public string DH_AFTER_TRIP_OPT3 { get; set; }
        public string DH_AFTER_TRIP_OPT2_REMARK { get; set; }
        public string DH_REMARK { get; set; }
        public string DH_AFTER_TRIP_OPT3_REMARK { get; set; }
        public string DH_CITY { get; set; }
        public Nullable<decimal> DH_TOTAL_PERSON { get; set; }
        public Nullable<System.DateTime> DH_CREATE_DATE { get; set; }
        public Nullable<decimal> DH_DOC_STATUS { get; set; }
        public string DH_CREATE_BY { get; set; }
        public string DH_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> DH_UPDATE_DATE { get; set; }
        public string DH_EXPENSE_OPT1 { get; set; }
        public string DH_EXPENSE_OPT2 { get; set; }
        public string DH_EXPENSE_REMARK { get; set; }
        public string DH_REMARK_REJECT { get; set; }
        public string DH_TYPE_FLOW { get; set; }
    }
}
