//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace top.ebiz.service
{ 
    using System; 

    public class configApp
    {
        // ใช้ IConfiguration เพื่อดึง key string จาก appsettings.json
        public static string GetStringFromAppSettings(string key)
        {
            // สร้าง IConfiguration เพื่ออ่านไฟล์ appsettings.json
            var config = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("appsettings.json")
                .Build();

            // ดึงค่าจาก key ที่ระบุใน appsettings.json
            return config[key] ?? ""; // หรือ config.GetSection(key).Value ก็ได้
        } 

    }
    public partial class VW_BZ_USERS
    {
        public string EMPLOYEEID { get; set; }
        public string USERID { get; set; }
        public string EMAIL { get; set; }
        public string USERDISPLAY { get; set; }
        public string THNAME { get; set; }
        public string THTITLE { get; set; }
        public string THFIRSTNAME { get; set; }
        public string THLASTNAME { get; set; }
        public string ENTITLE { get; set; }
        public string ENFIRSTNAME { get; set; }
        public string ENLASTNAME { get; set; }
    }
    public class DocHeadModel
    {
        public string document_status { get; set; }
        public string DH_CODE { get; set; }
        public Nullable<decimal> DH_VERSION { get; set; }
        public Nullable<decimal> DH_DOC_STATUS { get; set; }
        public Nullable<System.DateTime> DH_DATE { get; set; }
        public string DH_COM_CODE { get; set; }
        public string DH_TYPE { get; set; }
        public string DH_BEHALF_EMP_ID { get; set; }
        public string ENNAME { get; set; }
        public string COMPANYCODE { get; set; }
        public string COMPANYNAME { get; set; }
        public string DH_TOPIC { get; set; }
        public string DH_TRAVEL { get; set; }
        public Nullable<System.DateTime> DH_BUS_FROMDATE { get; set; }
        public string bus_start { get; set; }
        public Nullable<System.DateTime> DH_BUS_TODATE { get; set; }
        public string bus_stop { get; set; }
        public Nullable<System.DateTime> DH_TRAVEL_FROMDATE { get; set; }
        public string travel_start { get; set; }
        public Nullable<System.DateTime> DH_TRAVEL_TODATE { get; set; }
        public string travel_stop { get; set; }
        public Nullable<decimal> DH_TRAVEL_DAYS { get; set; }
        public string DH_TRAVEL_OBJECT { get; set; }
        public string DH_INITIATOR_EMPID { get; set; }
        public string INITIATOR_NAME { get; set; }
        public string INITIATOR_COM { get; set; }
        public string DH_INITIATOR_REMARK { get; set; }
        public string DH_AFTER_TRIP_OPT1 { get; set; }
        public string DH_AFTER_TRIP_OPT2 { get; set; }
        public string DH_AFTER_TRIP_OPT3 { get; set; }
        public string DH_AFTER_TRIP_OPT2_REMARK { get; set; }
        public string DH_REMARK { get; set; }
        public string DH_AFTER_TRIP_OPT3_REMARK { get; set; }
        public string DH_CITY { get; set; }
        public Nullable<decimal> DH_TOTAL_PERSON { get; set; }
        public Nullable<System.DateTime> DH_CREATE_DATE { get; set; }


        //DevFix 20210527 0000 เพิ่มข้อมูล ประเภทใบงานเป็น 1:flow, 2:not flow, 3:training เก็บไว้ที่  BZ_DOC_HEAD.DH_TYPE_FLOW
        public string DH_TYPE_FLOW { get; set; }

        //DevFix 20210622 0000 เพิ่มข้อมูล ประเภทพนักงาน 1:Employee, 2:Contract
        public string REQUEST_USER_TYPE { get; set; }
        public string REQUEST_USER_NAME { get; set; }
    }


}
