//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace top.ebiz.service
{
    using System;
    using System.Collections.Generic;
    
    public partial class BZ_USERS
    {
        public string EMPLOYEEID { get; set; }
        public string USERID { get; set; }
        public string COMPANYCODE { get; set; }
        public string FUNCTION { get; set; }
        public string DEPARTMENT { get; set; }
        public string DIVISION { get; set; }
        public string SECTIONS { get; set; }
        public string UNITS { get; set; }
        public string ORGID { get; set; }
        public string POSID { get; set; }
        public string OBJENFULLNAME { get; set; }
        public string OBJTHFULLNAME { get; set; }
        public string POSCAT { get; set; }
        public string EMPSTATUS { get; set; }
        public string EMPCAT { get; set; }
        public string PERSAREA { get; set; }
        public string PERSUBAREA { get; set; }
        public string EMPGROUP { get; set; }
        public string EMPSUBGROUP { get; set; }
        public string THNAME { get; set; }
        public string THTITLE { get; set; }
        public string THFIRSTNAME { get; set; }
        public string THLASTNAME { get; set; }
        public string ENTITLE { get; set; }
        public string ENFIRSTNAME { get; set; }
        public string ENLASTNAME { get; set; }
        public string GENDER { get; set; }
        public string REFERENCEID { get; set; }
        public string EMAIL { get; set; }
        public string SUPERVISOR { get; set; }
        public string MANAGERIAL { get; set; }
        public string CONTRACT { get; set; }
        public string HOLDERPOSITION { get; set; }
        public string REPORTTOPOS { get; set; }
        public string REPORTTOID { get; set; }
        public string REPORTTONAME { get; set; }
        public string REPORTTOEMAIL { get; set; }
        public string TOKEN { get; set; }
        public string IMGURL { get; set; }
        public string ORGNAME { get; set; }
        public string MANAGER_EMPID { get; set; }
        public string SH { get; set; }
        public string VP { get; set; }
        public string AEP { get; set; }
        public string EVP { get; set; }
        public string SEVP { get; set; }
        public string CEO { get; set; }
        public string COSTCENTER { get; set; }
        public Nullable<decimal> USERSTATUS { get; set; }
        public string ACTION { get; set; }
        public Nullable<System.DateTime> ACTION_DATE { get; set; }
        public Nullable<System.DateTime> UPDATEDDATE { get; set; }
        public Nullable<decimal> ROLE_ID { get; set; }
        public string EMPPOS { get; set; }
        public string ORDERWBS { get; set; }
        public string GLACCOUNT { get; set; }
        public string USERTYPE { get; set; }
    }
     

}
